apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-c
  name: service-c
spec:
  ports:
  - name: http-metrics
    port: 3003
    protocol: TCP
    targetPort: 3003
  selector:
    app: service-c
  type: ClusterIP
status:
  loadBalancer: {}
