apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-a
  name: service-a
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3001
  selector:
    app: service-a
  # type: LoadBalancer
status:
  loadBalancer: {}
